[project]
name = "nyc-mta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.127.1",
    "nyct-gtfs>=2.1.0",
    "uvicorn>=0.40.0",
    "playwright>=1.40.0",
]
